mysql:
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=123456
  volumes:
   - /my/own/datadir:/var/lib/mysql

app:
  image: relateiq/oracle-java8
  expose:
   - "8080"
  links:
   - mysql
  volumes:
   - ./build/libs/dengo-erp-0.0.1-SNAPSHOT.jar:/app.jar
  command: java -jar app.jar --dbUrl=mysql
