hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    erp-server:
        path: /erp/**
        serviceId: erp-server
        stripPrefix: false
        sensitiveHeaders:

    tachometerMicroService:
        path: /tachometer/**
        serviceId: tachometerMicroService
        stripPrefix: false
        sensitiveHeaders:

    auth-service:
        path: /uaa/**
        url: http://auth-service:5000
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 80
