security:
  oauth2:
    client:
      clientId: erp-server
      clientSecret: e123456
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  context-path: /erp
  port: 8000

spring:
  application:
    host: erp-server
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl-auto: create-drop
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
#    username: root
#    password: 123456

