security:
  oauth2:
    client:
      clientId: tachometerMicroService
      clientSecret: t123456
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server


server:
  context-path: /tachometer
  port: 3780

spring:
  application:
    host: tachometerMicroService